---
title: "NFL WR Combine Analysis"
output: html_document
date: "2026-05-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
# Install these only once
install.packages("readxl")
install.packages("readr")

# Load packages
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(stringr)
library(tidyr)

# Read the Excel career file
career_data <- read_excel(
  "C:/Users/24mmc/OneDrive - University of Wisconsin - Platteville/Spring Semesters/Spring 26/Data Science 1/Final Project/sportsref_download.xlsx"
)

# Read the combine CSV file
combine_data <- read_csv(
  "C:/Users/24mmc/OneDrive - University of Wisconsin - Platteville/Spring Semesters/Spring 26/Data Science 1/Final Project/NFL_Combine_Since_2000.csv"
)
combine_wr <- combine_data %>%
  filter(Position == "WR")

career_wr <- career_data %>%
  filter(
    Pos == "WR",
    From >= 2000
  )

# Check that they loaded
head(career_data)
head(combine_data)

# See column names
names(career_data)
names(combine_data)
```



```{r}
clean_names <- function(x) {
  x %>%
    str_to_lower() %>%
    str_replace_all("\\.", "") %>%
    str_replace_all(" jr", "") %>%
    str_replace_all(" iii", "") %>%
    str_replace_all(" ii", "") %>%
    str_squish()
}

career_wr$Player <- clean_names(career_wr$Player)
combine_wr$Player <- clean_names(combine_wr$Player)

merged_data <- inner_join(career_wr, combine_wr, by = c("Player", "From" = "Year")) %>%
  distinct() %>%
  rename(Draft_Team = Team.y, Career_AV = AV...3, Forty = "40-yd Dash") %>%
  
  select(-AV...9, -Team.x, -Rk, -Position) %>%
  
  mutate(
    Seasons = To - From + 1,
    AV_per_season = Career_AV / Seasons
  )
names(merged_data) <- names(merged_data) %>%
  gsub(" ", "_", .) %>%
  gsub("-", "_", .)
head(merged_data)
nrow(merged_data)
```




```{r}
merged_data %>%
  count(Player) %>%
  filter(n > 1)

merged_data %>%
  filter(Player == "kyle williams")
```


```{r}
combine_wr %>%
  count(Player) %>%
  filter(n > 1)
```


```{r}
# combine metrics to graph
combine_metrics <- c(
  "Forty",
  "Vertical_Jump",
  "Bench_Press",
  "Broad_Jump",
  "3_Cone_Drill",
  "20_yd_Shuttle"
)

# make sure they are numeric
merged_data[combine_metrics] <- lapply(
  merged_data[combine_metrics],
  as.numeric
)

# graph all metrics
for(metric in combine_metrics) {
  
  p <- ggplot(
    merged_data,
    aes(x = .data[[metric]], y = AV_per_season)
  ) +
    geom_point(alpha = 0.5) +
    geom_smooth(method = "lm", se = FALSE) +
    labs(
      title = paste(metric, "vs AV Per Season"),
      x = metric,
      y = "AV Per Season"
    )
  
  print(p)
}
```
```{r}
model <- lm(
  AV_per_season ~ Forty +
    Vertical_Jump +
    Bench_Press +
    Broad_Jump +
    `3_Cone_Drill` +
    `20_yd_Shuttle`,
  data = merged_data
)

summary(model)
```



